### ISSUE TITLE
Review `condition` types

### ISSUE THREAD

**Issue by sergeysova** [effector/patronum#109]
![image](https://user-images.githubusercontent.com/5620073/97091454-a2cf1680-1644-11eb-9e33-cd612d3aa4f7.png)

**Comment by sergeysova** [comment]
`then` and `else` allows `Unit<void>` in union (`Unit<T> | Unit<void>` or `Unit<T | void>` doesnt matter).
When `Event<T>` passed to `else` it comes as `T` assigning to `T | void`, but also it is requires `T | void` for `else`, but passed `T`.

**Comment by ainursharaev** [comment]
> `then` and `else` allows `Unit<void>` in union (`Unit<T> | Unit<void>` or `Unit<T | void>` doesnt matter). When `Event<T>` passed to `else` it comes as `T` assigning to `T | void`, but also it is requires `T | void` for `else`, but passed `T`.

Could you please reproduce the issue?
