### ISSUE TITLE
Debounce throws error when timeout is zero

### ISSUE THREAD

**Issue by RicheyRyan** [effector/patronum#128]
The `debounce` function throws an error when given `0` as a `timeout`. The error message indicates that `0` should be valid but the condition is wrong:

https://github.com/effector/patronum/blob/ae4b0d5654796f5954af17ecc494a32d67381eaf/debounce/index.js#L16-L17

Allowing `0` as a valid value would be useful for me in the context of a helper that sets up various things for HTTP queries. 

I'd be more than happy to PR the change, just let me know.

**Comment by sergeysova** [comment]
@RicheyRyan Thank you for your report. The bug lies in other code. I'll fix it

**Comment by RicheyRyan** [comment]
Thanks for getting back to me so quickly and fixing the issue too. I appreciate it!

**Comment by sergeysova** [comment]
Released in https://github.com/effector/patronum/releases/tag/v1.1.0
