### ISSUE TITLE
Add `currentTime` operator

### ISSUE THREAD

**Issue by igorkamyshev** [effector/patronum#152]
I found an interesting pattern in Aviasales codebase. In many cases we use `Date.now` and `new Date()`, and now we have no Effector-way to handle it.

Maybe we can add utility function for `currentTime` store creation to `patronum`? What do you think?

References:
+ Mobx — https://github.com/mobxjs/mobx-utils#now

If you are OK with it, I'll send a PR with my proposal, and we can discuss API and implementation.

**Comment by zerobias** [comment]
I don't quite understand why mobx couldn't get around to calling Date.now() directly, is there some other nuance besides `createStore(Date.now())`? I feel like I'm missing something important

**Comment by igorkamyshev** [comment]
If I create new store and wait for 4 minutes, I'll find too old value in the store.

**Comment by igorkamyshev** [comment]
I can describe our use case more specific. Now we have store $exploreId. Each explore I should contain the hash of current time, origin and destination of current search.

So, I would like to create this store with something like this

```
const $exploreId = combine($origin, $destination, $currentTime, makeHash)
```

**Comment by zerobias** [comment]
How often $currentTime updated? Is this adjustable? Looks like I have a use case for this one: change animation on a fly, but it happens 16 times per second

**Comment by igorkamyshev** [comment]
I think, we should provide a way to configure update frequency. Something like this

```ts
const $currentTime = currentTime({ interval?: 300, stop?: eventForStop, restart?: eventForRestart })
```

**Comment by sergeysova** [comment]
What about an effect to get current time on demand

**Comment by igorkamyshev** [comment]
> What about an effect to get current time on demand

It's a good idea, sure. But in some cases it can be impossible. For example, if I have timer on page. Something like "only 10 minutes left".

**Comment by sergeysova** [comment]
Maybe it is better to create `interval`?

```js
const { tick, opened } = interval({ timeout: 300, start: event, stop: event });

sample({
  clock: tick,
  target: readTimeFx,
})

// or (bad example) but take an idea
$time.on(tick, () => Date.now())
```

**Comment by igorkamyshev** [comment]
Looks like working example. But why don't add currentTime and skip this boring code in project?

**Comment by igorkamyshev** [comment]
So, `interval` + `time` is a better way for handling this situation.

**Comment by sergeysova** [comment]
I propose that interface:

```ts
const $now = time({ clock, getNow?: () => Date.now() })
```
