### ISSUE TITLE
Convert tests to TypeScript

### ISSUE THREAD

**Issue by doasync** [effector/patronum#16]
- [x] `combine-events`
- [x] `condition` (#87)
- [x] `debounce`
- [x] `debug` (#89)
- [x] `delay`
- [x] `every` (#88)
- [x] `inFlight` (#84)
- [x] `pending` (#82)
- [x] `reshape` (#89)
- [x] `some`
- [x] `split-map`
- [x] `spread` (#89)
- [x] `status` (#89)
- [x] `throttle`

**Comment by sergeysova** [comment]
@doasync We can do it but also we need to write type tests for failures

**Comment by sergeysova** [comment]
https://github.com/sergeysova/patronum/issues/22
