### ISSUE TITLE
Create `readonly` method

### ISSUE THREAD

**Issue by igorkamyshev** [effector/patronum#161]
# Abstract

In some cases, I should forbid store modification by external modules.

For example, when I write `userService`, I want to encapsulate all modification in this service and provide something like `readonly` store for the rest of the application.

Example:

```ts
// user_service.ts
const $userName = createStore('')
  .on(userNamedChanged, (_, newName) => newName)
  .on(fecthUserNameFx.doneData, (_, fetchedName) => fetchedName)

const userService = { $uerName: readonly($userName) }

export default userService
```

```ts
// other_file_in_the_project.ts

import userService from './user_service'

// It's the rest of the application 🌚
```

So, here I want to forbid `.on` calls on `userService.$userName` and usage `userService.$userName` as a target in any operators.

# Motivation

Encapsulation of write operations is a good way to structure any program. So, I think, we need a way to forbid writes to stores in some cases.

**Comment by sergeysova** [comment]
Implicit: https://share.effector.dev/TBtJRKG3
Explicit: https://share.effector.dev/j3DMfGDf

By @yumauri
