### ISSUE TITLE
`condition` doesn't work with type guards

### ISSUE THREAD

**Issue by fsher** [effector/patronum#166]
Hey there!

I've discovered that `condition`'s `if` doesn't propagate type guarded types to `else` and `then`. When passing a union type in `source` return type and trying to type-guard it in `if`, `else` still has `Unit<void | NoInfer<Foo | Bar>`

[Reproducible Example](https://www.typescriptlang.org/play?ts=4.3.5#code/JYWwDg9gTgLgBAbwMYQHYBNg2GgvnAMyghDgCIwBDGY1AVxDIG4AoUSWRJKAU2p4CiANx6oY+IiXI8CBHkhjRmLFjACeYHnABiECHAC8iQnoBccAM41gqAOZxcrdZrgAhSlEPGARh-NWoG3tHFRRUKzhgC119IwAKAj1fKHMYuAAfNw8ASnNEiGTIix09QwA+OASkjzhKYpjsgDp8uABCAyM6DBkbHnRWFjCInhExL24+GEFRmAAeNMz3KDK47NYh+HzhUXgjCf5tsXm9FbXBtAjkw924fanr2aXTgbDMbDQ4hBY4Swg6KCQPHMIx2ABpvpECOY4uhqJRcnBYTBKEUSrEKlEYjC4dlwT8APT4uAAFQ0WlsdA8mDsiIgPAsqAA5PAAO7QADWjS5EJgAAtRHk9Nc8XAeAAbCxAuBXGYsXDZFRAA)

**Expected Result**
* `else` and `then` properties are type guarded by `if`, similar to effector's `guard`

**Environment:**
* Effector: 22.1.0
* Typescript: 4.3.5

Please let me know if you need more information regarding this. Thanks!

**Comment by fsher** [comment]
May be linked to #109

**Comment by sergeysova** [comment]
@fsher Can you reproduce your example again? I can't see any issues

**Comment by ainursharaev** [comment]
@fsher I've checked your example and also didn't get any issues
