### ISSUE TITLE
Catch could not resolve dependency: peer effector@^21.4.0 error when deploying my react app to netlify

### ISSUE THREAD

**Issue by MiiZZo** [effector/patronum#171]
Effector dependencies in my project:
"effector": "^22.1.1",
"effector-react": "^22.0.4",
"patronum": "^1.1.0",

**Comment by sergeysova** [comment]
@MiiZZo You can try to update to `next` version:

```bash
yarn add patronum@next
# or
npm add patronum@next
```

**Comment by binjospookie** [comment]
Looks like patronum@1.7.0 supports effector >= 22.1.2

**Comment by sergeysova** [comment]
https://github.com/effector/patronum/releases/tag/v1.7.0
