### ISSUE TITLE
Batch store updates with `spread` 

### ISSUE THREAD

**Issue by Kelin2025** [effector/patronum#183]
Since `spread` uses separate `sample` statement for each provided target, effector does not batch store updates
```tsx
spread({
  source: somethingHappened,
  targets: { a: storeA, b: storeB, c: storeC }
})

combine([storeA, storeB, storeC]).watch(console.log)

somethingHappened({ a: 1, b: 2, c: 3 }) // Will re-calculate combine three times
```
Suggested fix is to check target type and, if it's a store, do `store.on(source, ...)` instead of `sample(...)`

**Comment by sergeysova** [comment]
@Kelin2025 Can you add test for this behaviour?
