### ISSUE TITLE
Short `some/every` variation

### ISSUE THREAD

**Issue by Kelin2025** [effector/patronum#191]
Most of the time `some` / `every` are used for checking booleans, because you 
- Either map different conditions to boolean format **before** passing them to `every`
- Check stuff which is boolean already (e.g. multiple pending effects)

Comparing multiple stores with the same value type (at least for me) is a very rare case, so passing predicate everytime here feels too excessive
So it would be good to have a shorter version of these methods
```tsx
every([$foo, $bar])
// =
every({
  predicate: true,
  stores: [$foo, $bar]
})
```

**Comment by sergeysova** [comment]
I think it is better to stay predicate argument:

```ts
every([$foo, $bar], true)
```

**Comment by igorkamyshev** [comment]
For me, `true` looks like good default in `every` and `some`. This piece of code `some([$first, $second])` could be read naturally as `some of $first or $second`.

**Comment by sergeysova** [comment]
I think `some of $first or $second` looks like `first || second` and should **return** first or second, don't compare it with value. As we see in javascript
