### ISSUE TITLE
operators and / or have problems with types 

### ISSUE THREAD

**Issue by ilyaagarkov** [effector/patronum#206]
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQZRtNOAXzgDMoIQ4AiNU0tZfKagKFElkTgwDsATADRxoxMhSrUwWCrwCuIagG5WrZBF4BneABJtBAIxwAvCnRZczNAAoAzAEo1G7XD1WATCbOZseAncdWPn5rN0NhMPR3R2hQ-XQDCPi0aNVVIA

**Comment by sergeysova** [comment]
Released in https://github.com/effector/patronum/releases/tag/v1.8.5
