### ISSUE TITLE
`delay` doesn't allow to use `void` in `target`

### ISSUE THREAD

**Issue by mindyourlifeguide** [effector/patronum#235]
The effect in the target expects void, a conditional number arrives from doneData - a mismatch in delay types

example:

```ts
delay({
    source: someFirstFx.doneData,
    timeout: 1000,
    target: someSecondFx,
});
```

**Comment by sergeysova** [comment]
Could you add a reproduce in https://www.typescriptlang.org/play ?

**Comment by mindyourlifeguide** [comment]
@sergeysova [check this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYBsCGBPOBfOAMyghDgHIxMYSA7AVxHIG4AoUSWROAYylWqoAooUKoe8AsVIVUo8TGgtWrHhFoBneBtKoAYsCha9ADzgBeXv0EixEgBT2AlOYB8SfjHpRacOPYQ8J3wnVXUtOB0QVABlcXVkUwsrARhheQd7WkxogC4tKGBaAHMXdzhPb19s6IA6RQBVMDBUKABhTA1UZxCVNCxsANY-Px1vHlRcyN0DIxhTWuR1VAARakwAGmGRmFBUCHoYKYBGAAZzrZG4GEwoYtQj6ei4tVpEky2g5iA)

**Comment by mindyourlifeguide** [comment]
the second effect takes data from the store via attach

**Comment by mindyourlifeguide** [comment]
maybe in delay we need to be able to choose between source/clock?

**Comment by sergeysova** [comment]
Okay, I transformed your example into minimal reproduce:

```ts
import { delay } from 'patronum';
import { createEvent } from 'effector';

const input = createEvent<string>()
const output = createEvent<void>();

delay({
    source: input,
    timeout: 1000,
    target: output,
});
```

[Try it](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYBsCGBPOBfOAMyghDgHIxMYSA7AVxHIG4AoUSWROAYylWqoAogDdUteAWKkKqQoVQ8Y0Fq1Y8ItAM7xgtMPXgBeXv0GjxMADw6oegOYA+ABQBKdZp1wIhg8dMCMMJiElYiEMDILq5srGhY2M4IrHCpcFo+UDyoAFxwen4ANClpMKCoPjB5AIwADPXFaXAwmFD2qFXevobFeDFqQA)

**Comment by mindyourlifeguide** [comment]
more complete [example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYBsCGBPOBfOAMyghDgHIxMYSA7AVxHIG4AoUSWROAYylWqoAooUKoeMADS9+ggMoxoqadRiYeACwLFSFVKPGKoLVqx4RaAZ3gASS6VQBJZHAC8MgTFQKlACnIAjOQAlKbmVvD2IKgAYsBQ1jEAHm4egiJiEr6+wa4AfEj8MPRQtHBwvgh4wfihZhbWcFHe4hbIyamq6hqVrOXl9iU8qABc3MDIY3YOzviSff36mTCVcBO1iAv9-UUlZRMAdIoAqmBgqFAAwpiWqFtzrNVsrGhY2L3bg1DDY81xCTBkgdkBZUAARaiYebbGCgVAQegwMYBAAMaOh-TUUAA5qgkU0HHJWrR2kl5k8gA)

**Comment by k0lyan** [comment]
You could solve it in userland. Something like this will work.
```ts
delay({
  source: sample({
    clock: input,
    fn: () => {},
  }),
  timeout: 1000,
  target: output,
});
```
