### ISSUE TITLE
`Reset` method overload

### ISSUE THREAD

**Issue by binjospookie** [effector/patronum#271]
I think it would be great if `reset` could only take target  and return an event. 

For example:
```typescript
const evt = reset({ target: [$a, $b, $c] });

evt(); // stores are now in defaults
```

There will eventually be 2 options:

```typescript
reset({ clock: evt, target: [$a, $b, $c] });

or

const evt = reset({ target: [$a, $b, $c] });
```

What do you think about it? 
I can send a PR if the idea is accepted.

**Comment by binjospookie** [comment]
**Example of use**

I need to clear stores when the feature is not used by the user. 
So I need to write smth like this:
```typescript
import { createEvent } from 'effector';
import { reset } from 'patronum'; 

import { $a } from 'model/a';
import { $b } from 'model/b';

const resetStores = createEvent();
reset({ clock: resetStores, target: [$a, $b] });

export { resetStores };
```

If we add the suggested change, the code will become more concise:
```typescript
import { reset } from 'patronum'; 

import { $a } from 'model/a';
import { $b } from 'model/b';

const resetStores = reset({ target: [$a, $b] });

export { resetStores };
```

**Comment by sergeysova** [comment]
@binjospookie Looks good.
Can you make a PR with code, docs, and tests?

**Comment by binjospookie** [comment]
Yes, I will soon

Is this [guide](https://github.com/effector/patronum/blob/main/CONTRIBUTING.md) up to date?

**Comment by sergeysova** [comment]
Yep.
Type tests located here https://github.com/effector/patronum/tree/main/test-typings

**Comment by binjospookie** [comment]
Thank you!
