### ISSUE TITLE
fix types for combineEvents

### ISSUE THREAD

**Issue by besizzo** [effector/patronum#273]
Using combineEvents in sample breaks types for provided payload

example: 

```ts
sample({
  clock: combineEvents({
    events: [deleteConfigInitiated, deleteConfigFx.done],  // types are OK 
  }),
  source: $idsInEditProcess, // types are OK
  fn: (idsInEditProcess, clock) => { // types are :any here 
    const updatedIds = idsInEditProcess((id) => id !== clock[0])
    return updatedIds
  },
  target: $idsInEditProcess,
})
```

According to @igorkamyshev it could be fixed like this:
![telegram-cloud-photo-size-2-5429453345434749142-y](https://user-images.githubusercontent.com/17437295/218773428-352ed719-5e85-462b-9e92-8e2b97f7d6f1.jpg)

Unfortunately, cannot make a PR by myself.

**Comment by sergeysova** [comment]
@besizzo Would you like to create reproduce in tsplay.dev?
It would be very helpful
