### ISSUE TITLE
Return `Store` and `StoreWritable<T>` whenever it is meaningful

### ISSUE THREAD

**Issue by agadoev** [effector/patronum#275]
Now in the documentation and `reshape` function signature return value is `Store`, but in fact it is `ReadonlyStore`. It can be reproduced by decomposing some stores with reshape and trying to modify it with `.on()`. An error message will appear in the browser console.

I suggest explicitly defining ReadonlyStore type as the return value of reshape function.

**Comment by agadoev** [comment]
now this code
```
const { $contentTemplate }= reshape({
  source: $complexData,
  shape: {
    $part1: (complexData) => complexData.part1,
    $part2: (complexData) => complexData.part2
  }
})
```

is the same as this code
```
const $part1 = $complexData.map(complexData => complexData.part1)
const $part2 = $complexData.map(complexData => complexData.part2)
```

I think it would be really useful if reshape returned a simple store, changing which would cause the parent store changes.

**Comment by sergeysova** [comment]
@agadoev At the moment effector do not defined `DerivedStore`. https://github.com/effector/effector/blob/master/packages/effector/index.d.ts

It will be possible only after this change.
Keep track of https://github.com/effector/effector/issues/755

**Comment by sergeysova** [comment]
`Store` renamed into `StoreWritable`, but `ReadonlyStore` renamed into `Store`

**Comment by sergeysova** [comment]
Released in https://github.com/effector/patronum/releases/tag/v2.0.0
