### ISSUE TITLE
debounce typing does not support void

### ISSUE THREAD

**Issue by StanislavMyakishev** [effector/patronum#277]
I've noticed that if I use `Event<void>` as the target with some parametrised `Event` as the source in `debounce` typing fails as it's waiting for the same param and not making an exception for void params.

It goes like this

```ts
const someParamEvent = createEvent<number>();
const someVoidEvent = createEvent();

// Fails with:  Type 'void' is not assignable to type 'number'.ts(2769)
const debounced = debounce({
  source: someParamEvent,
  timeout: 300,
  target: someVoidEvent
});
```

[reproduce link](https://codesandbox.io/s/xenodochial-wu-tz4c0k?file=/src/App.tsx:186-284)

And tysm for the work you put in this awesome library. I really enjoy using it in my projects 😄

**Comment by igorkamyshev** [comment]
Thanks for report 🫶 sound like a good first issue, huh? do you want to take it?

**Comment by Yasir761** [comment]
I want to give it a try, I think I can solve resolve it.
