### ISSUE TITLE
Allow array of targets in `delay`

### ISSUE THREAD

**Issue by Kelin2025** [effector/patronum#287]
<img width="420" alt="image" src="https://github.com/effector/patronum/assets/4208480/0e7ded40-258f-4361-b447-cb6039f62ee0">

Current `target` type is `Store<T> | Event<T> | Effect<T, any, any> | Event<void> | Effect<void, any, any>`

Would be cool to add `Target[]` to this, but I'm curious if this was an intentional decision

**Comment by sergeysova** [comment]
@Kelin2025 Thank you for the feature request. I think it can be implemented.
Would you like to make PR?
