### ISSUE TITLE
Remove `forward` using

### ISSUE THREAD

**Issue by sergeysova** [effector/patronum#292]
- [ ] https://github.com/effector/patronum/blob/f439c040257a6478da6cebd65ab55c1ecabc0e0f/src/delay/index.ts#L4
- [ ] https://github.com/effector/patronum/blob/f439c040257a6478da6cebd65ab55c1ecabc0e0f/src/condition/index.ts#L2
- [ ] https://github.com/effector/patronum/blob/f439c040257a6478da6cebd65ab55c1ecabc0e0f/src/spread/index.ts#L2
- [ ] https://github.com/effector/patronum/blob/f439c040257a6478da6cebd65ab55c1ecabc0e0f/src/interval/index.ts#L6

**Comment by zerobias** [comment]
Released in patronum 2.0
