### ISSUE TITLE
Add `createToggle ` operator

### ISSUE THREAD

**Issue by sagdeev** [effector/patronum#294]
Hi! What do you think about new method `createToggle`? We often use the on/off state in our work. Can be used for popup or notify. Perhaps need a different name 🤔

Something like this:

```typescript
const { $enabled, on, off, toggle, reset } = createToggle(false);
```

If everything is ok I can implement this 😃

**Comment by sergeysova** [comment]
Not sure it is for `patronum`. Because patronum is the library of operators, not typical model factories.

But need to ask @AlexandrHoroshih and @igorkamyshev

**Comment by igorkamyshev** [comment]
> Not sure it is for `patronum`. Because patronum is the library of operators, not typical model factories.
> 
> 
> 
> But need to ask @AlexandrHoroshih and @igorkamyshev 

timeout, debounce, and, or, equals, either, etc 

So, almost all functions in patronum is **factories**. They creates some units and returns it.

**Comment by sergeysova** [comment]
Maybe we need to choose a new name for this method?

**Comment by AlexandrHoroshih** [comment]
I actually think, it is a pretty good name 😄 

It could be shortened to fit more of "patronum naming style", like `const someToggle = toggle(false)`, but this way it is a bit less obvios, what this thing actually does

**Comment by AlexandrHoroshih** [comment]
Actually, there is already a similiar proposal
https://github.com/effector/patronum/issues/286

Looks like `toggler` it is a pretty good name!
